# Generated by Django 4.0.3 on 2022-03-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-03-07 11:17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonces',
            name='description',
            field=models.TextField(default='test test descrition ou peut-etre lorem ipsum dolor sit amet'),
            preserve_default=False,
        ),
    ]
