# Generated by Django 4.0.3 on 2022-03-07 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_annonces_created_at_annonces_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
