# Generated by Django 4.0.3 on 2022-03-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_annonces_band'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annonces',
            new_name='Listing',
        ),
    ]
