# Generated by Django 4.0.3 on 2022-03-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_annonces_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock'), ('RG', 'Reggae'), ('JZ', 'Jazz'), ('SY', 'Soyoyo'), ('SB', 'Seben'), ('ZL', 'Zinli'), ('AFB', 'Afrobeat')], max_length=5, null=True),
        ),
    ]
